name: Lint

on:
  push:
  pull_request:
  schedule:
  # 00:00 UTC every Saturday, don't bother anyone
  - cron: '0 0 * * 6'

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install build
        run: pip install build
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt
      - name: Build and install package
        run: python -m build -w && pip install dist/crc32c*.whl
      - name: Run mypy
        run: mypy --strict src test
      - name: Run black
        run: black --check .
      - name: Run isort
        run: isort --profile black --check --diff .
